spring:
  application:
    name: order2cash
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  data-path: ${APP_DATA_PATH:/data}

logging:
  level:
    com.example.order2cash: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level --- %msg%n"
